apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstonecluster
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstonecluster
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate    
  template:
    metadata:
      labels:
        app: capstonecluster
    spec:
      containers:
      - name: capstonecluster
        image: kalyan212/capstonecluster:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 5000