# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version:  2.1
jobs:
  lint_check:
    docker:
    # Use the same Docker base as the project
      - image: python:3.7.3-stretch

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv devops
            . devops/bin/activate
            make install
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64
            chmod +x /bin/hadolint
            
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . devops/bin/activate
            make lint
  # building the docker app
  build_docker_app:
    environment:
      IMAGE_VERSION:  v1
    docker:
      - image: circleci/golang:1.15
     
    steps:
      - checkout
      - setup_remote_docker

      # Build the image and push Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t test1:$IMAGE_VERSION .
      - run:
          name: List Docker Image
          command: |
            docker image ls
      - run:
          name: Push Docker Image
          command: |
            docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_PASS"
            dockerpath=$IMAGE_NAME:$IMAGE_VERSION
            docker push $dockerpath
            
            
            
workflows:
  version:   2.1
  default:
    jobs:
      - lint_check
      - build_docker_app:
          requires: [lint_check]
      